swagger: '2.0'

info:
  version: "0.0.1"
  title: service-hmlFhirConverter
  description: Mid level API to handle services of web-hmlFhirAngularClient

schemes:
  - https
  
basePath: /v1

produces:
  - application/json

paths:
  /hml/typingtTestNames/{size}:
    get:
      operationId: getTypingTestNames
      description: Gets the list of available typing test names
      parameters:
        -
          name: size
          in: query
          description: Number of results returned
          required: true
          type: number
          format: int32
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfTypingTestNames
            type: array
            items:
              $ref: '#/definitions/TypingTestName'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
  /hml/typingTestName:
    post:
      operationId: createTestingTypeName
      description: Creates a typing test name entry
      

definitions:
  Error:
    type: object
    properties:
      exception:
        type: string
        description: Explanation of exception thrown
      message:
        type: string
        description: Exception message
  TypingTestName:
    type: object
    properties:
      id:
        type: string
        description: GUID id of testing type name
      name:
        type: string
        description: Display / Common name of typing test
      description:
        type: string
        description: Description of typing test name