swagger: '2.0'

info:
  version: "0.0.1"
  title: service-hmlFhirConverter
  description: Mid level API to handle services of web-hmlFhirAngularClient

schemes:
  - https
  
basePath: /v1

produces:
  - application/json

paths:
  /typingTestName/get/{id}:
    get:
      operationId: getTypingTestName
      description: Gets the typing test name by Id
      parameters:
        -
          name: id
          in: query
          description: Id of typing test name in database
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/TypingTestName'
        500:
          description: Internal Server Error
          schema:
            title: HmlControllerException
            schema:
              $ref: '#/definitions/Error'
  /typingTestName/delete/{id}:
    get:
      operationId: deleteTypingTestName
      description: Deletes the typing test name by Id
      parameters:
        -
          name: id
          in: query
          description: Id of typing test name in database
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            title: BooleanOfSuccessfulOperation
            type: boolean
        500:
          description: Internal Server Error
          schema:
            title: TypingTestNameControllerException
            schema:
              $ref: '#/definitions/Error'
  /typingTestName/getMulti/{maxResults}:
    get:
      operationId: getTypingTestNames
      description: Gets the list of available typing test names
      parameters:
        -
          name: maxResults
          in: query
          description: Number of results returned
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfTypingTestNames
            type: array
            items:
              $ref: '#/definitions/TypingTestName'
        500:
          description: Internal Server Error
          schema:
            title: TypingTestNameControllerException
            schema:
              $ref: '#/definitions/HmlControllerException'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
  /typingTestName/create:
    post:
      operationId: createTypingTestName
      description: Creates a typing test name entry
      parameters:
        -
          name: typingTestName
          in: body
          description: Typing Test Name Object
          required: true
          schema:
            $ref: '#/definitions/TypingTestName'
      responses:
        200:
          description: Successful response
          schema:
              $ref: '#/definitions/TypingTestName'
        500:
          description: Internal Server Error
          schema:
            title: TypingTestNameControllerException
            schema:
              $ref: '#/definitions/Error'
  /typingTestName/createMulti:
    post:
      operationId: createTypingTestNames
      description: Create multiple testing type name entries
      parameters:
        -
          name: typingTestNames
          in: body
          description: Array of Typing Test Name Objects
          required: true
          schema:
            title: ArrayOfTypingTestNames
            type: array
            items:
              $ref: '#/definitions/TypingTestName'
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfTypingTestNames
            type: array
            items:
              $ref: '#/definitions/TypingTestName'
        500:
          description: Internal Server Error
          schema:
            title: TypingTestNameControllerException
            schema:
              $ref: '#/definitions/Error'
  /typingTestName/update:
    put:
      operationId: updateTypingTestName
      description: Update a single typing test name entry
      parameters:
        -
          name: typingTestName
          in: body
          description: Typing Test Name Object
          required: true
          schema:
            $ref: '#/definitions/TypingTestName'
      responses:
        200:
          description: Successful response
          schema:
              $ref: '#/definitions/TypingTestName'
        500:
          description: Internal Server Error
          schema:
            title: TypingTestNameControllerException
            schema:
              $ref: '#/definitions/Error'
  /typingTestName/delete:
    post:
      operationId: deleteTypingTestName
      description: Delete a single typing test name entry
      parameters:
        -
          name: typingTestName
          in: body
          description: Typing Test Name Object
          required: true
          schema:
            $ref: '#/definitions/TypingTestName'
      responses:
        200:
          description: Successful response
          schema:
            title: BooleanOfSuccessfulOperation
            type: boolean
        500:
          description: Internal Server Error
          schema:
            title: TypingTestNameControllerException
            schema:
              $ref: '#/definitions/Error'
definitions:
  TypingTestNameControllerException:
    type: object
    properties:
      httpStatus:
        type: string
        description: Http status code
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  ReportingCenter:
    type: object
    properties:
      id:
        type: string
        description: Id of reporting center
      context:
        type: string
        description: Context of reporting center
      active:
        type: boolean
        description: Active center
      dateCreated:
        type: string
        format: date-time
        description: Creation date
  TypingTestName:
    type: object
    properties:
      id:
        type: string
        description: Id of testing type name
      name:
        type: string
        description: Display / Common name of typing test
      description:
        type: string
        description: Description of typing test name
      active:
        type: boolean
        description: Active record
      dateCreated:
        type: string
        format: date-time
        description: Creation date