swagger: '2.0'

info:
  version: "0.0.1"
  title: service-hmlFhirConverter
  description: Mid level API to handle services of web-hmlFhirAngularClient

schemes:
  - https
  
basePath: /v1

produces:
  - application/json

paths:
  /hml/typingtTestNames/{maxResults}:
    get:
      operationId: getTypingTestNames
      description: Gets the list of available typing test names
      parameters:
        -
          name: maxResults
          in: query
          description: Number of results returned
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfTypingTestNames
            type: array
            items:
              $ref: '#/definitions/TypingTestName'
        500:
          description: Internal Server Error
          schema:
            title: HmlControllerException
            schema:
              $ref: '#/definitions/HmlControllerException'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
  /hml/typingTestName:
    post:
      operationId: createTestingTypeName
      description: Creates a typing test name entry
      

definitions:
  HmlControllerException:
    type: object
    properties:
      httpStatus:
        type: string
        description: Http status code
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  TypingTestName:
    type: object
    properties:
      id:
        type: string
        description: GUID id of testing type name
      name:
        type: string
        description: Display / Common name of typing test
      description:
        type: string
        description: Description of typing test name
      active:
        type: boolean
        description: Active record
      dateCreated:
        type: date
        description: Date created